// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// sparsediff.cpp
std::string sd_engine_version();
extern "C" SEXP _sparsediff_sd_engine_version() {
  BEGIN_CPP11
    return cpp11::as_sexp(sd_engine_version());
  END_CPP11
}
// sparsediff.cpp
doubles sd_selftest_dgemm();
extern "C" SEXP _sparsediff_sd_selftest_dgemm() {
  BEGIN_CPP11
    return cpp11::as_sexp(sd_selftest_dgemm());
  END_CPP11
}
// sparsediff.cpp
SEXP sd_variable(int d1, int d2, int var_id, int n_vars);
extern "C" SEXP _sparsediff_sd_variable(SEXP d1, SEXP d2, SEXP var_id, SEXP n_vars) {
  BEGIN_CPP11
    return cpp11::as_sexp(sd_variable(cpp11::as_cpp<cpp11::decay_t<int>>(d1), cpp11::as_cpp<cpp11::decay_t<int>>(d2), cpp11::as_cpp<cpp11::decay_t<int>>(var_id), cpp11::as_cpp<cpp11::decay_t<int>>(n_vars)));
  END_CPP11
}
// sparsediff.cpp
SEXP sd_exp(SEXP child);
extern "C" SEXP _sparsediff_sd_exp(SEXP child) {
  BEGIN_CPP11
    return cpp11::as_sexp(sd_exp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(child)));
  END_CPP11
}
// sparsediff.cpp
SEXP sd_neg(SEXP child);
extern "C" SEXP _sparsediff_sd_neg(SEXP child) {
  BEGIN_CPP11
    return cpp11::as_sexp(sd_neg(cpp11::as_cpp<cpp11::decay_t<SEXP>>(child)));
  END_CPP11
}
// sparsediff.cpp
SEXP sd_add(SEXP left, SEXP right);
extern "C" SEXP _sparsediff_sd_add(SEXP left, SEXP right) {
  BEGIN_CPP11
    return cpp11::as_sexp(sd_add(cpp11::as_cpp<cpp11::decay_t<SEXP>>(left), cpp11::as_cpp<cpp11::decay_t<SEXP>>(right)));
  END_CPP11
}
// sparsediff.cpp
SEXP sd_sum(SEXP child, int axis);
extern "C" SEXP _sparsediff_sd_sum(SEXP child, SEXP axis) {
  BEGIN_CPP11
    return cpp11::as_sexp(sd_sum(cpp11::as_cpp<cpp11::decay_t<SEXP>>(child), cpp11::as_cpp<cpp11::decay_t<int>>(axis)));
  END_CPP11
}
// sparsediff.cpp
SEXP sd_problem(SEXP objective, list constraints, bool verbose);
extern "C" SEXP _sparsediff_sd_problem(SEXP objective, SEXP constraints, SEXP verbose) {
  BEGIN_CPP11
    return cpp11::as_sexp(sd_problem(cpp11::as_cpp<cpp11::decay_t<SEXP>>(objective), cpp11::as_cpp<cpp11::decay_t<list>>(constraints), cpp11::as_cpp<cpp11::decay_t<bool>>(verbose)));
  END_CPP11
}
// sparsediff.cpp
void sd_init_jacobian(SEXP prob);
extern "C" SEXP _sparsediff_sd_init_jacobian(SEXP prob) {
  BEGIN_CPP11
    sd_init_jacobian(cpp11::as_cpp<cpp11::decay_t<SEXP>>(prob));
    return R_NilValue;
  END_CPP11
}
// sparsediff.cpp
void sd_init_derivatives(SEXP prob);
extern "C" SEXP _sparsediff_sd_init_derivatives(SEXP prob) {
  BEGIN_CPP11
    sd_init_derivatives(cpp11::as_cpp<cpp11::decay_t<SEXP>>(prob));
    return R_NilValue;
  END_CPP11
}
// sparsediff.cpp
double sd_objective_forward(SEXP prob, doubles u);
extern "C" SEXP _sparsediff_sd_objective_forward(SEXP prob, SEXP u) {
  BEGIN_CPP11
    return cpp11::as_sexp(sd_objective_forward(cpp11::as_cpp<cpp11::decay_t<SEXP>>(prob), cpp11::as_cpp<cpp11::decay_t<doubles>>(u)));
  END_CPP11
}
// sparsediff.cpp
doubles sd_gradient(SEXP prob);
extern "C" SEXP _sparsediff_sd_gradient(SEXP prob) {
  BEGIN_CPP11
    return cpp11::as_sexp(sd_gradient(cpp11::as_cpp<cpp11::decay_t<SEXP>>(prob)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_sparsediff_sd_add",               (DL_FUNC) &_sparsediff_sd_add,               2},
    {"_sparsediff_sd_engine_version",    (DL_FUNC) &_sparsediff_sd_engine_version,    0},
    {"_sparsediff_sd_exp",               (DL_FUNC) &_sparsediff_sd_exp,               1},
    {"_sparsediff_sd_gradient",          (DL_FUNC) &_sparsediff_sd_gradient,          1},
    {"_sparsediff_sd_init_derivatives",  (DL_FUNC) &_sparsediff_sd_init_derivatives,  1},
    {"_sparsediff_sd_init_jacobian",     (DL_FUNC) &_sparsediff_sd_init_jacobian,     1},
    {"_sparsediff_sd_neg",               (DL_FUNC) &_sparsediff_sd_neg,               1},
    {"_sparsediff_sd_objective_forward", (DL_FUNC) &_sparsediff_sd_objective_forward, 2},
    {"_sparsediff_sd_problem",           (DL_FUNC) &_sparsediff_sd_problem,           3},
    {"_sparsediff_sd_selftest_dgemm",    (DL_FUNC) &_sparsediff_sd_selftest_dgemm,    0},
    {"_sparsediff_sd_sum",               (DL_FUNC) &_sparsediff_sd_sum,               2},
    {"_sparsediff_sd_variable",          (DL_FUNC) &_sparsediff_sd_variable,          4},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_sparsediff(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
