# Generated by cpp11: do not edit by hand

sd_engine_version <- function() {
  .Call(`_sparsediff_sd_engine_version`)
}

sd_selftest_dgemm <- function() {
  .Call(`_sparsediff_sd_selftest_dgemm`)
}

sd_variable <- function(d1, d2, var_id, n_vars) {
  .Call(`_sparsediff_sd_variable`, d1, d2, var_id, n_vars)
}

sd_exp <- function(child) {
  .Call(`_sparsediff_sd_exp`, child)
}

sd_neg <- function(child) {
  .Call(`_sparsediff_sd_neg`, child)
}

sd_add <- function(left, right) {
  .Call(`_sparsediff_sd_add`, left, right)
}

sd_sum <- function(child, axis) {
  .Call(`_sparsediff_sd_sum`, child, axis)
}

sd_problem <- function(objective, constraints, verbose) {
  .Call(`_sparsediff_sd_problem`, objective, constraints, verbose)
}

sd_init_jacobian <- function(prob) {
  invisible(.Call(`_sparsediff_sd_init_jacobian`, prob))
}

sd_init_derivatives <- function(prob) {
  invisible(.Call(`_sparsediff_sd_init_derivatives`, prob))
}

sd_objective_forward <- function(prob, u) {
  .Call(`_sparsediff_sd_objective_forward`, prob, u)
}

sd_gradient <- function(prob) {
  .Call(`_sparsediff_sd_gradient`, prob)
}
